# Generated by Django 5.2.9 on 2025-12-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income"), ("transfer", "Transfer")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("currency_from", models.CharField(max_length=8)),
                ("currency_to", models.CharField(max_length=8)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_converted", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_recurrence", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("created", models.DateField(db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="account", to="core.account"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="category", to="core.category"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="tags", to="core.tag")),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
