# Generated by Django 5.2.9 on 2025-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("expense", "Expense"),
                    ("income", "Income"),
                    ("transfer", "Transfer"),
                    ("correction", "Correction"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
